config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :fixpoints, except: [:destroy] do
    resources :fixpoint_attachments, except: [:index]
    member do
      patch :set_fixed
    end
    resources :votes, only: [:create, :destroy]
  end
end

app/models/fixpoint.rb
# == Schema Information
#
# Table name: fixpoints
#
#  id         :bigint           not null, primary key
#  fixed      :boolean
#  fix_date   :date
#  latitude   :float
#  longitude  :float
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  category   :integer
#  user_id    :bigint
#

class Fixpoint < ApplicationRecord
  has_many :votes
  has_many :fixpoint_attachments
  belongs_to :user

  accepts_nested_attributes_for :fixpoint_attachments

  enum category: [:aesthetics, :pollution, :accessibility, :hazard]

  geocoded_by :address # add geocode by IP
  reverse_geocoded_by :latitude, :longitude

  reverse_geocoded_by :latitude, :longitude do |fixp, results|
    if geo = results.first
      fixp.address = [geo.street, geo.house_number].join(', ')
    end
  end

  after_validation :geocode, :reverse_geocode

  validates :fixpoint_attachments, presence: true
  # validates :latitude, presence: true
  # validates :longitude, presence: true


  validates :category, :user, presence: true
  validates :address, presence: true, if: ->(fp) { !fp.latitude || !fp.longitude }

  # validate do |fixpoint|
  #   fixpoint.errors.add(:base, "Photo is missing!") if fixpoint.fixpoint_attachments.blank?
  # end
end

app/controllers/fixpoints_controller.rb
class FixpointsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_fixpoint, only: [:show, :edit, :update, :set_fixed]

  def index
    @fixpoints = policy_scope(Fixpoint).order("created_at DESC")

    if params[:filter] == 'fixed'
      @fixpoints = policy_scope(Fixpoint).where(fixed: true)
    elsif params[:filter] == 'not-fixed'
      @fixpoints = policy_scope(Fixpoint).where(fixed: false)
    elsif params[:filter] == 'my-fixes'
      @fixpoints = current_user.fixpoints.where.not(latitude: nil, longitude: nil)
    end

    @markers = @fixpoints.order(:created_at).map do |fixpoint|
      {
        lat: fixpoint.latitude,
        lng: fixpoint.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { fixpoint: fixpoint }),
        image_url: url_for_marker(fixpoint),
        newly_created: params[:newly_created_id].to_i == fixpoint.id
      }
    end
  end

  def show
    @fixpoint_attachments = @fixpoint.fixpoint_attachments.all
    authorize @fixpoint
  end

  def new
    @fixpoint = Fixpoint.new
    @fixpoint_attachment = @fixpoint.fixpoint_attachments.build
    authorize @fixpoint
  end

  def create
    @fixpoint = Fixpoint.new(fixpoint_params)
    @fixpoint.user = current_user

    if params[:fixpoint_attachments]
      build_photos
    else
      @fixpoint.fixpoint_attachments.build
    end

    authorize @fixpoint

    if @fixpoint.save
      path = fixpoints_path(
        center_lat: @fixpoint.latitude,
        center_lon: @fixpoint.longitude,
        newly_created_id: @fixpoint.id
      )

      redirect_to path, notice: 'fixpoint was successfully created.'
    else
      render action: 'new'
    end
  end

  def edit
    authorize @fixpoint
  end

  def update
    if @fixpoint.update(fixpoint_params)
      redirect_to @fixpoint
    else
      render :edit
    end
  end

  def set_fixed
    authorize @fixpoint

    @fixpoint.fixed = !@fixpoint.fixed

    if @fixpoint.save
      respond_to do |format|
        format.html { redirect_to new_fixpoint_fixpoint_attachment_path(@fixpoint) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
        flash[:notice] = "It is really easy to share a photo of the fix. 📸"
      end
    end
  end

  private

  def build_photos
    params[:fixpoint_attachments]['photo'].each do |photo|
      @fixpoint.fixpoint_attachments.build(photo: photo)
    end
  end

  def set_fixpoint
    @fixpoint = Fixpoint.find(params[:id])
  end

  def fixpoint_params
    params.require(:fixpoint).permit(:address, :category, :longitude, :latitude, :fix_date, :fixed,
                                     fixpoint_attachments_attributes: [:id, :fixpoint_id, :photo])
  end

  def url_for_marker(fixpoint)
    if fixpoint.user == current_user
      helpers.asset_url('placeholder3.png')
    elsif fixpoint.fixed? == false
      helpers.asset_url('placeholder1.png')
    else
      helpers.asset_url('placeholder2.png')
    end
  end
end

app/views/fixpoints/_card.html.erb
<div class="card_fix">
  <div class="card">
    <% if fixpoint.fixed? %>
     <%= render 'fixpoints/images_fixed', fixpoint: fixpoint %>
    <% else %>
     <%= render 'fixpoints/images', fixpoint: fixpoint %>
    <% end %>
    <% if user_signed_in? %>
    <div class="card-status <%= fixpoint.fixed ? 'background-fixed' : 'background-hazard' %>">
      <% if current_user.admin? %>
        <% if fixpoint.fixed? %>
        <!-- Button to Open the Modal -->
          <%= link_to set_fixed_fixpoint_path(fixpoint),style: '    padding-top: 5px;', method: :patch, remote: true do %>
            <i class="far fa-check-square"></i>
            Fixed!
          <% end %>
          <%= link_to '#', {data: { toggle: "modal", target: "#fixpoint_#{fixpoint.id}"}} do %>
          <i class="fas fa-camera photo_icon"></i>
          <% end %>
        <% else %>
          <%= link_to set_fixed_fixpoint_path(fixpoint),style: '    padding-top: 5px;', method: :patch,remote: true do %>
            <button class="button-fixed" type="button" data-hover="Fix it!" data-active="I'M ACTIVE"><span>To fix</span></button>
          <% end %>
        <% end %>
      <% else %>
        <span><%= fixpoint.fixed ? 'Fixed' : 'Not fixed' %></span>
      <% end %>
    </div>
    <% else %>
    <div class="card-status-logout <%= fixpoint.fixed ? 'background-fixed' : 'background-hazard' %>">
    </div>
    <% end %>
    <div class="card-body text-dark">
      <div class="card-main-header">
        <% if user_signed_in? %>
        <% if fixpoint.user == current_user %>
          <div class="user-avatar bg-primary">
            <%= fixpoint.user.initials %>
          </div>
        <% else %>
          <div class="user-avatar bg-secondary">
            <%= fixpoint.user.initials %>
          </div>
        <% end %>
        <% end %>
        <div>
          <p><%= fixpoint.address %></p>
          <% if fixpoint.fixed? %>
          <p><small class="text-muted">Fixed in <%= distance_of_time_in_words(fixpoint.updated_at-fixpoint.created_at) %></small></p>
          <% else %>
          <p><small class="text-muted">Created <%= time_ago_in_words(fixpoint.created_at) %> ago</small></p>
          <% end %>
        </div>
      </div>
      <div class="card-main-footer">
        <div>
          <% if fixpoint.aesthetics? %>
            <span class="badge badge-primary"><%= fixpoint.category %></span>
          <% end %>
          <% if fixpoint.pollution? %>
            <span class="badge badge-warning"><%= fixpoint.category %></span>
          <% end %>
          <% if fixpoint.hazard? %>
            <span class="badge badge-danger"><%= fixpoint.category %></span>
          <% end %>
          <% if fixpoint.accessibility? %>
            <span class="badge badge-success"><%= fixpoint.category %></span>
          <% end %>
        </div>
        <% if user_signed_in? %>
        <% unless current_user.admin? %>
        <%= render "shared/votes", fixpoint: fixpoint %>
        <% else %>
        <div id="fixpoint_votes_<%= fixpoint.id %>" class="fixpoint-votes">
        <i class="fas fa-thumbs-up"></i>
        <span class="count">
        <%= fixpoint.votes.count %>
        </span>
      </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= render 'photosmodal_info', fixpoint: fixpoint %>

app/views/fixpoints/_fixpoints_list.html.erb
<div id="fixpoints-list" class="container">
  <div class="header">
    <% if params[:filter] == "my-fixes" %>
    <h1>My fixpoints</h1>
    <% elsif params[:filter] == "all" %>
    <h1>All fixpoints</h1>
    <% elsif params[:filter] == "not-fixed" %>
    <h1>To Fix</h1>
    <% elsif params[:filter] == "fixed" %>
    <h1>Fixed</h1>
    <% else %>
    <h1>No fixpoints</h1>
    <% end %>
  <hr>
  </div>
  <div class="row">
    <% if !@fixpoints.empty? %>
      <% fixpoints.each do |fixpoint| %>
        <div class="col-sm-12 col-md-6 col-lg-4">
          <%= render 'fixpoints/card', fixpoint: fixpoint %>
          <%= render 'photosmodal', fixpoint: fixpoint %>
        </div>
      <% end %>
    <% else %>
      <h1>No fixpoints</h1>
    <% end %>
  </div>
</div>

app/views/fixpoints/_form.html.erb
<%= simple_form_for @fixpoint do |f| %>
  <% if @fixpoint.errors.any? %>
  <div id="error_explanation">
   <div class="alert alert-error">
     The form contains <%= pluralize(@fixpoint.errors.count, "error") %>.
   </div>
  <ul>
   <% @fixpoint.errors.full_messages.each do |msg| %>
    <li>* <%= msg %></li>
   <% end %>
 </ul>
</div>
<% end %>

<%= f.input :category, as: :select, collection: Fixpoint.categories.keys.to_a %>
  <%= f.input :address %>

  <%= f.simple_fields_for :fixpoint_attachments do |faf| %>
    <%= faf.file_field :photo, multiple: true, name: "fixpoint_attachments[photo][]", label: "Photos" %>
  <% end %>

  <%= f.button :submit, class: 'btn btn-primary btn-lg btn-block mt-4' %>
<% end %>

app/views/fixpoints/_images.html.erb
<div id="fixpoint-images-carousel-<%= fixpoint.id %>" class="carousel slide" data-ride="carousel" data-interval="false">
  <div class="carousel-inner">
    <% fixpoint.fixpoint_attachments.each_with_index do |attachment, index| %>
      <% if fixpoint.fixed? %>
        <div class="carousel-item <%= fixpoint.fixpoint_attachments.last.id + 1 ? 'active' : '' %>">
        <%= cl_image_tag fixpoint.fixpoint_attachments.last.photo, class: 'd-block w-100', height: 200 %>
      </div>
      <% else %>
      <div class="carousel-item <%= index == 0 ? 'active' : '' %>">
      <%= cl_image_tag attachment.photo, class: 'd-block w-100', height: 200 %>
      </div>
      <% end %>
      <div class="carousel-item <%= index == 0 ? 'active' : '' %>">
        <%= cl_image_tag attachment.photo, class: 'd-block w-100', height: 200 %>
      </div>
    <% end %>
  </div>
  <% if fixpoint.fixpoint_attachments.size > 1 %>
    <a class="carousel-control-prev" href="#fixpoint-images-carousel-<%= fixpoint.id %>" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#fixpoint-images-carousel-<%= fixpoint.id %>" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  <% end %>
</div>

app/views/fixpoints/_images_fixed.html.erb
<div id="fixpoint-images-carousel-<%= fixpoint.id %>" class="carousel slide" data-ride="carousel" data-interval="false">
  <div class="carousel-inner">
    <% fixpoint.fixpoint_attachments.reverse_order.each_with_index do |attachment, index| %>
      <div class="carousel-item <%= index == 0 ? 'active' : '' %>">
        <%= cl_image_tag attachment.photo, class: 'd-block w-100', height: 200 %>
      </div>
    <% end %>
  </div>
  <% if fixpoint.fixpoint_attachments.size > 1 %>
    <a class="carousel-control-prev" href="#fixpoint-images-carousel-<%= fixpoint.id %>" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#fixpoint-images-carousel-<%= fixpoint.id %>" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  <% end %>
</div>

app/views/fixpoints/_infowindow.html.erb
<%= render 'fixpoints/card', fixpoint: fixpoint %>
<%= render 'photosmodal_info', fixpoint: fixpoint %>

app/views/fixpoints/_map.html.erb
<div class="a" id="map"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  data-center-lat="<%= params[:center_lat] %>"
  data-center-lon="<%= params[:center_lon] %>">
</div>

app/views/fixpoints/_modal_new.html.erb
<!-- The Modal -->
<div class="modal" id="fixpoint_new">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Add a new Fixpoint</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <p style="text-align: center;">We would love to see more info about that problem.
        <br> So our professionals can get to work on solving the problem.</p>
        <% @fixpoint = Fixpoint.new %>
        <% @fixpoint_attachment = @fixpoint.fixpoint_attachments.build %>
      <%= simple_form_for @fixpoint do |f| %>
        <% if @fixpoint.errors.any? %>
        <div id="error_explanation">
         <div class="alert alert-error">
           The form contains <%= pluralize(@fixpoint.errors.count, "error") %>.
         </div>
        <ul>
         <% @fixpoint.errors.full_messages.each do |msg| %>
          <li>* <%= msg %></li>
         <% end %>
       </ul>
      </div>
      <% end %>

      <%= f.input :category, as: :select, collection: Fixpoint.categories.keys.to_a %>
        <%= f.input :address %>

      <%= f.simple_fields_for :fixpoint_attachments do |faf| %>
        <%= faf.file_field :photo, multiple: true, name: "fixpoint_attachments[photo][]", label: "Photos" %>
        <% end %>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
      <%= f.button :submit,'Add Fixpoint', class: "btn-primary mb-2" %>
      <% end %>
      </div>

    </div>
  </div>
</div>

app/views/fixpoints/_photosmodal.html.erb
<!-- The Modal -->
<div class="modal" id="fixpoint_<%= fixpoint.id %>">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Show us your Photos</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <p style="text-align: center;">We would love to see pictures of the fixes.
        <br> So everyone can marvel at the new CityMakeover!</p>
      <%= simple_form_for [fixpoint, FixpointAttachment.new] do |f| %>
      <%= f.label :photos %>
      <%= f.file_field :photo,input_html: { class:"btn btn-success" } %>


      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
      <%= f.button :submit,'Add Photos', class: "btn-primary mb-2" %>
      <% end %>
      </div>

    </div>
  </div>
</div>

app/views/fixpoints/_photosmodal_info.html.erb
<!-- The Modal -->
<div class="modal" id="fixpoint_<%= fixpoint.id %>">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Show us your Photos</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <p style="text-align: center;">We would love to see pictures of the fixes.
        <br> So everyone can marvel at the new CityMakeover!</p>
      <%= simple_form_for [fixpoint, FixpointAttachment.new] do |f| %>
      <%= f.label :photos %>
      <%= f.file_field :photo,input_html: { class:"btn btn-success" } %>


      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
      <%= f.button :submit,'Add Photos', class: "btn-primary mb-2" %>
      <% end %>
      </div>

    </div>
  </div>
</div>

<style>

.modal-backdrop.show {
    opacity: inherit!important;
}

.modal-backdrop {
  position:inherit!important;
}
</style>

app/views/fixpoints/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 offset-md-3">
      <%= render "fixpoint_attachments/form" %>
    </div>
  </div>
</div>

app/views/fixpoints/index.html.erb
<%#= render 'fixpoints_list', fixpoints: @fixpoints %>

<%#= render "map" %>


<% if params[:view] == 'list' %>
  <%= render 'fixpoints_list', fixpoints: @fixpoints %>
<% else %>
  <%= render "map" %>
<% end %>

<div class="plus_button">
  <%= link_to "+", '#', {data: { toggle: "modal", target: "#fixpoint_new"}}%>
</div>

<div class="toggle_button">
  <%= link_to toggle_link, id: "toggle-list" do %>
    <% if params[:view] == 'list' %>
      <i class="fas fa-toggle-off"></i>
    <% else %>
      <i class="fas fa-toggle-on"></i>
    <% end %>
  <% end %>
</div>

<div class="b">
  <%= render 'shared/sidebar' %>
</div>

<%= render 'modal_new' %>

app/views/fixpoints/new.html.erb
<style>
  body {
    background-image: url("https://images.unsplash.com/photo-1445346366695-5bf62de05412?ixlib=rb-1.2.1&auto=format&fit=crop&w=1486&q=80")
  }
</style>

<div class="container">
  <div class="row justify-content-center">
    <div class="form-login col-12 col-md-6 col-lg-4">
      <%= render "form" %>
      <%= link_to "back to map", fixpoints_path %>
    </div>
  </div>
</div>

app/views/fixpoints/show.html.erb
<h1><%= @fixpoint %></h1>
<div>
  <div class="img">
    <%= image_tag ("photos/garbage1.jpeg")%><br>
    <% @fixpoint.created_at %> Created <%= time_ago_in_words(Date.today) %> ago
  </div>
  <div class="card-body">
    <p>
      <%= @fixpoint.category %>
      <br>
      <%= @fixpoint.latitude %><%= @fixpoint.longitude %>
      <br>
    </p>
  </div>
</div>
<%= link_to 'Back' %>
<% if @fixpoint.fixpoint_attachments.any? %>
  <div class="bd-example">
    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <%= image_tag @fixpoint.fixpoint_attachments.first.photo_url %>
          <div class="carousel-caption d-none d-md-block">
            <h5>Before fix</h5>
            <p>Taken ... ago</p>
          </div>
        </div>
        <div class="carousel-item">
          <%= image_tag @fixpoint.fixpoint_attachments.first.photo_url %>
          <div class="carousel-caption d-none d-md-block">
            <h5>After fix</h5>
            <p><% @fixpoint.fixpoint_attachments.first.created_at %> Created <%= time_ago_in_words(Date.today) %> ago</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
<% end %>
<%# This is the COUNTER! %>
<h2><%= @fixpoint.fixpoint_attachments.count %></h2>
<%# This creats the 'ADD PHOTO' link %>
<%= link_to "Add photo", new_fixpoint_fixpoint_attachment_path(@fixpoint) %>

<% @fixpoint.fixpoint_attachments.each do |fp_attch| %>
  <%= cl_image_tag fp_attch.photo, height: 300, width: 400, crop: :fill %>
  <%= link_to "change photo", edit_fixpoint_fixpoint_attachment_path(fp_attch.fixpoint, fp_attch) %>
  <%= link_to "delete photo", fixpoint_fixpoint_attachment_path(fp_attch.fixpoint, fp_attch), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>