config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :fixpoints, except: [:destroy] do
    resources :fixpoint_attachments, except: [:index]
    member do
      patch :set_fixed
    end
    resources :votes, only: [:create, :destroy]
  end
end

app/views/shared/_cards_fixpoints.html.erb
<div class="card-fixpoint">
  <div class="card-photo" >
    <% if fixpoint.fixpoint_attachments.present? %>
      <%= cl_image_tag fixpoint.fixpoint_attachments.first.photo %>
    <% else %>
      <%= image_tag('http://res.cloudinary.com/domeafay4/image/upload/v1559217010/rb3iyntwumo23d0vnapt.jpg') %>
    <% end %>
    <p class="card-date">Created <%= time_ago_in_words(fixpoint.created_at) %> ago</p>
  </div>
  <div>
    <h3 class="card-category"><%= fixpoint.category %></h2>
    <h2 class="card-adress"><%= fixpoint.address %></h3>
  <button type="button" class="btn btn-link"> <%= link_to "Add photos", new_fixpoint_fixpoint_attachment_path(fixpoint) %> </button>
  <div id="votes-map">
    <%= render "shared/votes", fixpoint: fixpoint %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<!-- Sidebar -->
<div class="sidebar w3-sidebar w3-bar-block w3-border-right" style="overflow-y: scroll; display: <%= params[:sidebar] ? "flex" : "none" %>;" id="mySidebar">
  <div class="sidebar-inner-container">
    <div>
      <button type="button" class="close" aria-label="Close" onclick="sidebarClose()">
        <span aria-hidden="true">&times;</span>
      </button>
      <% if user_signed_in? %>
      <div class="user-avatar bg-primary">
        <%= current_user.initials %>
      </div>

      <% end %>
    </div>
    <div class="sidebar-title">
      <h2>City Makeover</h2>
    </div>
    <div class="form">
      <div class="form-check">
        <label class="form-check-label">
          <%= radio_button_tag :filter, 'all', params[:filter] == 'all', class: 'sidebar-radio' %>
          All
        </label>
      </div>
      <div class="form-check">
        <label class="form-check-label">
          <%= radio_button_tag :filter, 'fixed', params[:filter] == 'fixed', class: 'sidebar-radio' %>
          Fixed
        </label>
      </div>
      <div class="form-check">
        <label class="form-check-label">
          <%= radio_button_tag :filter, 'not-fixed', params[:filter] == 'not-fixed', class: 'sidebar-radio' %>
          Not fixed
        </label>
      </div>
      <% if user_signed_in? %>
      <div class="form-check">
        <label class="form-check-label">
          <%= radio_button_tag :filter, 'my-fixes', params[:filter] == 'my-fixes', class: 'sidebar-radio' %>
          My fixes
        </label>
      </div>
      <% end %>
    </div>
    <div class="bottom-area">
      <% if user_signed_in? %>
        <%= link_to destroy_user_session_path, method: :delete, class: 'login-btn btn btn-primary btn-lg btn-block' do %>
          Logout
        <% end %>
      <% else %>
        <%= link_to new_user_session_path, class: "login-btn btn btn-primary btn-lg btn-block" do %>
          Login
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<button class="sidebar-burger btn btn-primary" id="burger" onclick="sidebarOpen()" style="display: <%= params[:sidebar] ? "none" : "block" %>;">
  <i class="fas fa-bars"></i>
</button>
<script>
  function sidebarOpen() {
    document.getElementById("mySidebar").style.display = "flex";
    document.getElementById("burger").style.display = "none";
  }

  function sidebarClose() {
    document.getElementById("mySidebar").style.display = "none";
    document.getElementById("burger").style.display = "block";
  }

  (function() {
    var radios = document.getElementsByClassName('sidebar-radio');

    Array.prototype.forEach.call(radios, function(radio){
      radio.addEventListener('click', () => {
        var searchParams = new URLSearchParams(window.location.search);
        searchParams.set('filter', radio.value);
        searchParams.set('sidebar', true);
        window.location.search = searchParams.toString();
        sidebarOpen();
      })
    });
  })();
</script>

app/views/shared/_votes.html.erb
<div id="fixpoint_votes_<%= fixpoint.id %>" class="fixpoint-votes">
  <span class="count">
    <%= fixpoint.votes.count %>
  </span>
  <% if user_signed_in? %>
    <% if fixpoint.votes.where(user: current_user).any? %>
      <%= link_to fixpoint_vote_path(fixpoint, fixpoint.votes.where(fixpoint: fixpoint, user: current_user).first), method: :delete, remote: true do %>
        <i class="fas fa-thumbs-up"></i>
      <% end %>
    <% else %>
      <%= link_to fixpoint_votes_path(fixpoint), method: :post, remote: true do %>
        <i class="far fa-thumbs-up text-muted"></i>
      <% end %>
    <% end %>
  <% else %>
    <i class="far fa-thumbs-up text-muted"></i>
  <% end %>
</div>