config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :fixpoints, except: [:destroy] do
    resources :fixpoint_attachments, except: [:index]
    member do
      patch :set_fixed
    end
    resources :votes, only: [:create, :destroy]
  end
end

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url(https://images.unsplash.com/photo-1444212568492-d2799d30943b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2852&q=80">
  <div class="container">
    <h1>CityMakeover</h1>
    <p>Improving our communities together</p>
    <%= link_to 'Start now', fixpoints_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col mt-4 mb-4">
      <h1 class="text-center home-how-it-works">How it works</h1>
    </div>
  </div>
</div>

<div class="container p-1">
  <div class="row">
    <div class="col-md-3">
      <div class="home-card">
        <h1><i class="fas fa-exclamation-triangle"></i></h1>
        <h4>Issue</h4>
        <p>First you find the issue</p>
      </div>
    </div>


    <div class="col-md-3">
      <div class="home-card">
        <h1><i class="fas fa-camera"></i></h1>
        <h4>Photo</h4>
        <p>Snap and upload a photo</p>
      </div>
    </div>

    <div class="col-md-3">
      <div class="home-card">
        <h1><i class="fas fa-paper-plane"></i></h1>
        <h4>Submit</h4>
        <p>Submit and let others vote</p>
      </div>
    </div>

    <div class="col-md-3">
      <div class="home-card">
        <h1><i class="fas fa-wrench"></i></h1>
        <h4>Fix</h4>
        <p>And the city repairs</p>
      </div>
    </div>
  </div>
</div>

<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>

  <div class="footer-copyright">
   Pedro, Luis, & Fermin - Le Wagon Batch#243
  </div>
</div>